version: "3.8"

services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_data:/home/jovyan/work
    container_name: jupyter_lab
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - ./n8n_data:/home/node/.n8n
    container_name: n8n
    restart: unless-stopped

  anaconda:
    image: continuumio/anaconda3
    ports:
      - "9999:8888"
    volumes:
      - ./anaconda_data:/opt/notebooks
    working_dir: /opt/notebooks
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
    container_name: anaconda
    restart: unless-stopped
